// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Outputs
{

    [OutputType]
    public sealed class D1DatabaseBinding
    {
        public readonly string DatabaseId;
        public readonly string Name;

        [OutputConstructor]
        private D1DatabaseBinding(
            string databaseId,

            string name)
        {
            DatabaseId = databaseId;
            Name = name;
        }
    }
}
