// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Outputs
{

    [OutputType]
    public sealed class KVNamespaceBinding
    {
        public readonly string Name;
        public readonly string NamespaceId;

        [OutputConstructor]
        private KVNamespaceBinding(
            string name,

            string namespaceId)
        {
            Name = name;
            NamespaceId = namespaceId;
        }
    }
}
