// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Outputs
{

    [OutputType]
    public sealed class QueueBinding
    {
        public readonly string Name;
        public readonly string QueueName;

        [OutputConstructor]
        private QueueBinding(
            string name,

            string queueName)
        {
            Name = name;
            QueueName = queueName;
        }
    }
}
