// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Outputs
{

    [OutputType]
    public sealed class R2BucketBinding
    {
        public readonly string BucketName;
        public readonly string Name;

        [OutputConstructor]
        private R2BucketBinding(
            string bucketName,

            string name)
        {
            BucketName = bucketName;
            Name = name;
        }
    }
}
