// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Outputs
{

    [OutputType]
    public sealed class SecretTextBinding
    {
        public readonly string Name;
        public readonly string Text;

        [OutputConstructor]
        private SecretTextBinding(
            string name,

            string text)
        {
            Name = name;
            Text = text;
        }
    }
}
