# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .module_worker_script import *
from .provider import *
from .random import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_cr.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_cr.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cr",
  "mod": "index",
  "fqn": "pulumi_cr",
  "classes": {
   "cr:index:ModuleWorkerScript": "ModuleWorkerScript",
   "cr:index:Random": "Random"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cr",
  "token": "pulumi:providers:cr",
  "fqn": "pulumi_cr",
  "class": "Provider"
 }
]
"""
)
