// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AnalyticsEngineBinding {
    dataset: string;
    name: string;
}

export interface D1DatabaseBinding {
    databaseId: string;
    name: string;
}

export interface KVNamespaceBinding {
    name: string;
    namespaceId: string;
}

export interface PlainTextBinding {
    name: string;
    text: string;
}

export interface QueueBinding {
    name: string;
    queueName: string;
}

export interface R2BucketBinding {
    bucketName: string;
    name: string;
}

export interface SecretTextBinding {
    name: string;
    text: string;
}

export interface ServiceBinding {
    name: string;
    service: string;
}

