// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Inputs
{

    public sealed class AnalyticsEngineBindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataset", required: true)]
        public Input<string> Dataset { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public AnalyticsEngineBindingArgs()
        {
        }
        public static new AnalyticsEngineBindingArgs Empty => new AnalyticsEngineBindingArgs();
    }
}
