// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Inputs
{

    public sealed class D1DatabaseBindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("databaseId", required: true)]
        public Input<string> DatabaseId { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public D1DatabaseBindingArgs()
        {
        }
        public static new D1DatabaseBindingArgs Empty => new D1DatabaseBindingArgs();
    }
}
