// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Inputs
{

    public sealed class PlainTextBindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("text", required: true)]
        public Input<string> Text { get; set; } = null!;

        public PlainTextBindingArgs()
        {
        }
        public static new PlainTextBindingArgs Empty => new PlainTextBindingArgs();
    }
}
