// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cr.Inputs
{

    public sealed class QueueBindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("queueName", required: true)]
        public Input<string> QueueName { get; set; } = null!;

        public QueueBindingArgs()
        {
        }
        public static new QueueBindingArgs Empty => new QueueBindingArgs();
    }
}
